### PR TITLE
feat/poetry and cli

### PR DESCRIPTION
**Pull request by dni**
- add poetry
- remove unneeded requirements
- add git workflow for pytest
- add PublicKey.from_npub
- add CLI

screenshot-1672331924

### CODE REVIEW

**Comment by jeffthibault** [comment]
Thanks! This looks awesome. I am not familiar with poetry but will look into it soon.

**Comment by jeffthibault** [comment]
Can you make 93d628c4bb9bf857cf0a2772203f3fb0ce00e9f7 a separate PR? I'm happy to merge that now while I review the other stuff

**Comment by dni** [comment]
there you go https://github.com/jeffthibault/python-nostr/pull/22

**Comment by dni** [comment]
btw. something does not quite work with your poetry / pyproject setup. i get errors when i try to install or add packages.

```
dni@arch:~/repos/python-nostr (main %) $ poetry add click

[tool.poetry] section not found in /home/dni/repos/python-nostr/pyproject.toml
dni@arch:~/repos/python-nostr (main %) $ poetry install                                                                                                                     1

[tool.poetry] section not found in /home/dni/repos/python-nostr/pyproject.toml
```

**Comment by dni** [comment]
and i think the gold nugget from that PR is nostr/cli.py, i use it all the time ;D

**Pull request closed without merging**
