### PR TITLE
Preparing release infrastructure

### PR DESCRIPTION
**Pull request by k9ert**
Here is a proposal on how to go with a release infrastructure:
* setuptools is great to use but in the meantime it's proposing the use of [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)
* the dependencies are directly specified in `pyproject.toml`. The `requirements.txt` is rather for direct projects than for libraries. See the explanation [here](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py)
* Also the dependencies schould be as loose as possible as this is a library project. It's the task of the project which is using this library to tighten the dependencies or pin them entirely.
* I tested [setuptools-scm](https://github.com/pypa/setuptools_scm) and i already love it. It will determine the version automatically via the git. I'll make an example below

This is how to release:
```
git checkout main
pip3 install -e .
pip3 install build twine
# i assume the working directory is clean and we want to release this
git tag 0.0.1rc10
git checkout 0.0.1rc10
python3 -m build
# Let's publish the release
# We can first test the upload via https://test.pypi.org/
python3 -m twine upload --repository testpypi dist/*
# Now let's do it for real:
python3 -m twine upload --repository dist/*
```

# Still some ToDos
- [ ] Update the Readme files if this concept is accepted

### CODE REVIEW

**Comment by jeffthibault** [comment]
Hi @k9ert, thanks for the proposal! I agree we definitely need to do this. This will be my first time creating a pypi package so I appreciate any support you can provide.

I will review your proposal soon and read up on releasing packages but wanted to acknowledge that I saw this.

**Comment by k9ert** [comment]
Python packaging is confusing and has lots of options. However nothing is set in stone as releasing is a constant activity anyway and even though older releases ARE set in stone, there is nothing more boring as an old release, just create a new one if you want to change things.
So, don't try to be perfect, take an advice from Eric S. Raymond: [https://en.wikipedia.org/wiki/Release_early,_release_often](Release early, release often!)
image

**Comment by k9ert** [comment]
Because i was so impatient (and thought that i need to test this better) i've created a test-release on testpypi:

```
(.env) k9ert@mymachine➜  python-nostr git:(main) git checkout release_prep
Switched to branch 'release_prep'
Your branch is up to date with 'origin/release_prep'.
(.env) k9ert@mymachine➜  python-nostr git:(release_prep) git status               
On branch release_prep
Your branch is up to date with 'origin/release_prep'.

nothing to commit, working tree clean
(.env) k9ert@mymachine➜  python-nostr git:(release_prep) pip3 install -e .  
Obtaining file:///home/k9ert/src/python-nostr
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: pycparser>=2.21 in ./.env/lib/python3.10/site-packages (from nostr==0.0.1rc2) (2.21)
Requirement already satisfied: websocket-client>=1.3.3 in ./.env/lib/python3.10/site-packages (from nostr==0.0.1rc2) (1.4.2)
Requirement already satisfied: cryptography>=37.0.4 in ./.env/lib/python3.10/site-packages (from nostr==0.0.1rc2) (38.0.4)
Requirement already satisfied: cffi>=1.15.0 in ./.env/lib/python3.10/site-packages (from nostr==0.0.1rc2) (1.15.1)
Requirement already satisfied: secp256k1>=0.14.0 in ./.env/lib/python3.10/site-packages (from nostr==0.0.1rc2) (0.14.0)
Building wheels for collected packages: nostr
  Building editable for nostr (pyproject.toml) ... done
  Created wheel for nostr: filename=nostr-0.0.1rc2-0.editable-py3-none-any.whl size=5268 sha256=0bb13de64d4bf7e166843bde0a76abc9cd89ca7c79d4b64a4a2ca1251584200a
  Stored in directory: /tmp/pip-ephem-wheel-cache-e3t34qwi/wheels/bb/a2/48/bbc3aeeb0410aaf061af5c37109efe113179791f3f6feb9017
Successfully built nostr
Installing collected packages: nostr
  Attempting uninstall: nostr
    Found existing installation: nostr 0.0.1rc2
    Uninstalling nostr-0.0.1rc2:
      Successfully uninstalled nostr-0.0.1rc2
Successfully installed nostr-0.0.1rc2
(.env) k9ert@mymachine➜  python-nostr git:(release_prep) git tag 0.0.1rc3 
fatal: tag '0.0.1rc3' already exists
(.env) k9ert@mymachine ➜  python-nostr git:(release_prep) git tag 0.0.1rc4
(.env) k9ert@mymachine➜  python-nostr git:(release_prep) git checkout 0.0.1rc4 
Note: switching to '0.0.1rc4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 7d75e64 improving release infra
(.env) k9ert@mymachine➜  python-nostr git:(7d75e64) python3 -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (build, setuptools, setuptools-scm)
* Getting build dependencies for sdist...
running egg_info
writing nostr.egg-info/PKG-INFO
writing dependency_links to nostr.egg-info/dependency_links.txt
writing requirements to nostr.egg-info/requires.txt
writing top-level names to nostr.egg-info/top_level.txt
adding license file 'LICENSE'
writing manifest file 'nostr.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing nostr.egg-info/PKG-INFO
writing dependency_links to nostr.egg-info/dependency_links.txt
writing requirements to nostr.egg-info/requires.txt
writing top-level names to nostr.egg-info/top_level.txt
adding license file 'LICENSE'
writing manifest file 'nostr.egg-info/SOURCES.txt'
running check
creating nostr-0.0.1rc2
creating nostr-0.0.1rc2/nostr
creating nostr-0.0.1rc2/nostr.egg-info
creating nostr-0.0.1rc2/test
copying files to nostr-0.0.1rc2...
copying .gitignore -> nostr-0.0.1rc2
copying LICENSE -> nostr-0.0.1rc2
copying README.md -> nostr-0.0.1rc2
copying pyproject.toml -> nostr-0.0.1rc2
copying setup.py -> nostr-0.0.1rc2
copying nostr/__init__.py -> nostr-0.0.1rc2/nostr
copying nostr/_version.py -> nostr-0.0.1rc2/nostr
copying nostr/bech32.py -> nostr-0.0.1rc2/nostr
copying nostr/event.py -> nostr-0.0.1rc2/nostr
copying nostr/filter.py -> nostr-0.0.1rc2/nostr
copying nostr/key.py -> nostr-0.0.1rc2/nostr
copying nostr/message_pool.py -> nostr-0.0.1rc2/nostr
copying nostr/message_type.py -> nostr-0.0.1rc2/nostr
copying nostr/pow.py -> nostr-0.0.1rc2/nostr
copying nostr/relay.py -> nostr-0.0.1rc2/nostr
copying nostr/relay_manager.py -> nostr-0.0.1rc2/nostr
copying nostr/subscription.py -> nostr-0.0.1rc2/nostr
copying nostr.egg-info/PKG-INFO -> nostr-0.0.1rc2/nostr.egg-info
copying nostr.egg-info/SOURCES.txt -> nostr-0.0.1rc2/nostr.egg-info
copying nostr.egg-info/dependency_links.txt -> nostr-0.0.1rc2/nostr.egg-info
copying nostr.egg-info/requires.txt -> nostr-0.0.1rc2/nostr.egg-info
copying nostr.egg-info/top_level.txt -> nostr-0.0.1rc2/nostr.egg-info
copying test/README.md -> nostr-0.0.1rc2/test
copying test/test_key.py -> nostr-0.0.1rc2/test
Writing nostr-0.0.1rc2/setup.cfg
Creating tar archive
removing 'nostr-0.0.1rc2' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (build, setuptools, setuptools-scm)
* Getting build dependencies for wheel...
running egg_info
writing nostr.egg-info/PKG-INFO
writing dependency_links to nostr.egg-info/dependency_links.txt
writing requirements to nostr.egg-info/requires.txt
writing top-level names to nostr.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'nostr.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'nostr.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/nostr
copying nostr/relay_manager.py -> build/lib/nostr
copying nostr/message_type.py -> build/lib/nostr
copying nostr/bech32.py -> build/lib/nostr
copying nostr/pow.py -> build/lib/nostr
copying nostr/subscription.py -> build/lib/nostr
copying nostr/message_pool.py -> build/lib/nostr
copying nostr/filter.py -> build/lib/nostr
copying nostr/relay.py -> build/lib/nostr
copying nostr/key.py -> build/lib/nostr
copying nostr/event.py -> build/lib/nostr
copying nostr/__init__.py -> build/lib/nostr
copying nostr/_version.py -> build/lib/nostr
running egg_info
writing nostr.egg-info/PKG-INFO
writing dependency_links to nostr.egg-info/dependency_links.txt
writing requirements to nostr.egg-info/requires.txt
writing top-level names to nostr.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'nostr.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'nostr.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/relay_manager.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/message_type.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/bech32.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/pow.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/subscription.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/message_pool.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/filter.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/relay.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/key.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/event.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/__init__.py -> build/bdist.linux-x86_64/wheel/nostr
copying build/lib/nostr/_version.py -> build/bdist.linux-x86_64/wheel/nostr
running install_egg_info
Copying nostr.egg-info to build/bdist.linux-x86_64/wheel/nostr-0.0.1rc2-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/nostr-0.0.1rc2.dist-info/WHEEL
creating '/home/k9ert/src/python-nostr/dist/.tmp-ellr3pur/nostr-0.0.1rc2-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'nostr/__init__.py'
adding 'nostr/_version.py'
adding 'nostr/bech32.py'
adding 'nostr/event.py'
adding 'nostr/filter.py'
adding 'nostr/key.py'
adding 'nostr/message_pool.py'
adding 'nostr/message_type.py'
adding 'nostr/pow.py'
adding 'nostr/relay.py'
adding 'nostr/relay_manager.py'
adding 'nostr/subscription.py'
adding 'nostr-0.0.1rc2.dist-info/LICENSE'
adding 'nostr-0.0.1rc2.dist-info/METADATA'
adding 'nostr-0.0.1rc2.dist-info/WHEEL'
adding 'nostr-0.0.1rc2.dist-info/top_level.txt'
adding 'nostr-0.0.1rc2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built nostr-0.0.1rc2.tar.gz and nostr-0.0.1rc2-py3-none-any.whl    
(.env) k9ert@mymachine ➜  python-nostr git:(7d75e64) python3 -m twine upload --verbose --repository testpypi dist/nostr-0.0.1rc2*
Uploading distributions to https://test.pypi.org/legacy/
INFO     dist/nostr-0.0.1rc2-py3-none-any.whl (13.0 KB)                                      
INFO     dist/nostr-0.0.1rc2.tar.gz (11.9 KB)                                                
INFO     Querying keyring for username                                                       
Enter your username: __token__
INFO     Querying keyring for password                                                       
Enter your password: 
INFO     username: __token__                                                                 
INFO     password: <hidden>                                                                  
Uploading nostr-0.0.1rc2-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.4/22.4 kB • 00:00 • 79.4 MB/s
INFO     Response from https://test.pypi.org/legacy/:                                        
         200 OK                                                                              
Uploading nostr-0.0.1rc2.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 kB • 00:00 • 142.4 MB/s
INFO     Response from https://test.pypi.org/legacy/:                                        
         200 OK                                                                              

View at:
https://test.pypi.org/project/nostr/0.0.1rc2/
(.env) k9ert@mymachine➜  python-nostr git:(7d75e64)
```

In that case i needed to create a token upfront for the entire account because the the project did not yet existed:
https://test.pypi.org/manage/account/token/

After that, it's a good idea to create a token specifically for your project. If you want to test this as well with pypi, tell me and i'll add you to the project (as owner).

**Comment by dni** [comment]
heyho! cool i did not see this PR, i did something similar today https://github.com/jeffthibault/python-nostr/pull/18

i also added a small CLI with click and a github workflow for tests

**Comment by jeffthibault** [comment]
Okay, so I followed this proposal as well as some other guides online and was able to get a first release on pypi: https://pypi.org/project/nostr/

I have verified that it can be installed using `pip install nostr`

Please let me know if it works for you. Thanks again! 😄

**Comment by k9ert** [comment]
Worked great! So should i continue to modify the Documentation or do you prefer to merge #18 ?

**Comment by k9ert** [comment]
Oh, just realized that you seem to already merged all of it. So closing this PR!

**Pull request closed without merging**
